### ISSUE TITLE
ShipIt to Marketplace: No plug-in found with key com.company.jira.plugins.pluginname

### ISSUE THREAD

**Issue by cmhrpr** [mibexsoftware/shipit2marketplace#1]
Hi,

We're trying to integrate ShipIt into our build plan for our new JIRA plugin. The plugin .jar file is included as a hardcoded artefact (name does not change from pluginname-1.0.jar currently) which is included as a dependency in the root of the working directory for the Shipit job.

However, when we try and run the ShipIt job - with the plugin jar being present in the root of the directory - we receive the following error:
`ShipIt to Marketplace: No plug-in found with key com.company.jira.plugins.pluginname`

**Comment by mrueegg** [comment]
@cmhrpr Hi, please excuse my late response. 

What the plug-in does initially that could cause this error is that it does a lookup in the Marketplace with the plug-in key from the JAR file. Is there already a version in the Marketplace for this plug-in? If yes, you should see some more detailed error messages in the build log which would help me a lot to diagnose the error.
